version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports: ["2181:2181"]

  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    ports: ["9092:9092"]
    hostname: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=eventBus:1:1

  login:
    build: ./login
    ports:
      - "4007:4007"
    depends_on:
      - kafka

  contact:
    build: ./contacts
    ports:
      - "4006:4006"
    depends_on:
      - kafka
